{
 "title": "GPUs",
 "description": "Dashboard to get an overview of one server",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "query": "label_values(node_boot_time, instance)"
   },
   {
    "name": "gpu",
    "query": "label_values(dcgm_gpu_temp{instance=~\"$server\"}, gpu)"
   }
  ]
 },
 "panels": [
  {
   "title": "Idle GPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "cpu usage" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (gpu) (irate(dcgm_gpu_utilization{instance=\"$server\"}[5m])) )",
     "legendFormat": "{{gpu}}"
    }
   ]
  },
  {
   "title": "GPU Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dcgm_gpu_utilization{gpu=\"$gpu\",instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "GPU Temperature",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "expr": "dcgm_gpu_temp{gpu=\"$gpu\",instance=\"$server\"}"
    }
   ]
  },
  {
   "title": "GPU Frame Buffer Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "dcgm_fb_free{gpu=\"$gpu\",instance=\"$server\"} + dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"}",
     "legendFormat": "total frame buffer"
    },
    {
     "expr": "dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"}",
     "legendFormat": "frame buffer used"
    },
    {
     "expr": "dcgm_fb_free{gpu=\"$gpu\",instance=\"$server\"}",
     "legendFormat": "frame buffer free"
    }
   ]
  },
  {
   "title": "GPU Frame Buffer Utilization",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "(dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"} / (dcgm_fb_free{gpu=\"$gpu\",instance=\"$server\"} + dcgm_fb_used{gpu=\"$gpu\",instance=\"$server\"})) * 100"
    }
   ]
  },
  {
   "title": "GPU Power usage",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "format": "watt",
   "valueName": "avg",
   "targets": [
    {
     "expr": "dcgm_power_usage{gpu=\"$gpu\",instance=\"$server\"}"
    }
   ]
  }
 ]
}