apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: netdata-metrics-podmonitor
  labels:
    app: netdata
    release: prometheus
    jobLabel: netdata
spec:
  namespaceSelector:
    any: true
  selector:    
    matchLabels:
      app: netdata
      release: netdata
  podMetricsEndpoints:
  - port: http
    path: /api/v1/allmetrics?format=prometheus
    interval: 10s