apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/nfs-server-provisioner
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        persistence:
          enabled: true
          storageClass: 'nfs'
          size: 200Gi
        storageClass:
          defaultClass: true
        nodeSelector:
          kubernetes.io/hostname: k8-n1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-nfs-server-provisioner-0
spec:
  storageClassName: nfs
  capacity:
    storage: 200Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /mnt/sdb/data-nfs-server-provisioner-0
  claimRef:
    namespace: kube-system
    name: data-nfs-server-nfs-server-provisioner-0