apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-cluster-operator
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metrics
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/rabbitmq/operator
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-server
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: metrics
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: charts/rabbitmq/rabbitmq
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      values: |
        replicas: 1