apiVersion: v1
kind: Pod
metadata:
  name: dark-converter
  namespace: default
spec:
  containers:
  - name: dark-converter
    image: kphoen/dark-converter:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always